name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - run: poetry install
    - name: Lint with pyproject-flake8
      run: poetry run pflake8 --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with PyTest
      run: poetry run pytest